# Generated by Django 4.0.4 on 2022-05-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='latest_message',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='timestamp',
        ),
    ]
