# Generated by Django 4.0.4 on 2022-05-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_customuser_latest_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latest_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
